name: Prev's Blog
description: Developer blog.

markdown: kramdown
# highlighter: rouge
# highlighter: none
kramdown:
   syntax_highlighter_opts:
      disable : true

baseurl: /
google_analytics: 'UA-34015951-1'
disqus_shortname: 'prevdev'

url:            'https://prev.kr'
site_url:       'https://prev.kr'
author:         'Prev'
permalink:       /posts/:title/
future:         true

gems:
  - jekyll-redirect-from

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post